### PR TITLE
Customization

### PR DESCRIPTION
**Pull request by WilliBobadilla**
tested on flutter 1.22.3 with stable channel
1. adding the save method when you press save in the selection modal
2. adding the same style to the bottom bar of cancel, clear all, save
3. clear all icon default icon changed to Icons.restrore_from_trash, that is basically a trash
4. example new without the form widget, it is optional, because in the onSaved method you can already save your data 
5. the keyword new removed from all the files 
6. the README.md was updated with screenshoots of the examples, one without customization and the second one with customization, to campare the results

### CODE REVIEW

**Comment by slavap** [comment]
@hiddencaliber @WilliBobadilla 
Initially I wanted to include this PR to my "null safety" PR: https://github.com/hiddencaliber/flutter_multiselect/pull/33
But decide not to do that, because this PR is minor and button's colors changes, which are not needed by default.
Also onSaved call when Save pressed in modal is not needed, there is change callback for that.
I've changed icon on 'Clear All' button to Icons.clear_all in my PR.

**Comment by WilliBobadilla** [comment]
thank your for your feedback! don't worry, is very useful for me read your feedback!

**Comment by lcsvcn** [comment]
@WilliBobadilla One suggestion, give a more meaningful title. It would help other users and author to understand the idea 
behind this PR do without need to open and go through all files

None the less, awesome PR. Hope it gets be merged soon.

**Review by lcsvcn — CHANGES_REQUESTED** [review]
Wrong typo:
restrore_from_trash

**Comment by hiddencaliber** [comment]
@WilliBobadilla @slavap 👍

**Pull request merged**
